spring:
  graphql:
    path: /graphql
    tools:
      introspection-enabled: false
    graphiql:
      enabled: false

wavefront:
  application:
    name: graphql-library
    service: bp-graphql-server